name: Pipeline

on:
  push:
    paths:
      - 'database/monitors/*.json'
    branches:
      - master

jobs:
  CICD:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check JSON syntax
        uses: limitusus/json-syntax-check@v1
        with:
          pattern: "\\.json$"

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Check mandatory fields
        run: |
          python devscript/check_mandatory_fields.py

      - name: Build monitors.json file
        run: |
          export VERSION=$(python devscript/build_monitors_json.py)
          echo "::set-env name=VERSION::$VERSION"
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

      - name: Build MONITORS.md file
        run: |
          python devscript/build_monitors_md.py

      - uses: EndBug/add-and-commit@v7
        with:
          add: '["database/monitors.json","MONITORS.md"]'
          message: 'Update version ${{ env.VERSION }}'
          push: true

      - name: Publish release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: v${{ env.VERSION }}
          prerelease: false
          title: v${{ env.VERSION }}
          files: |
            ./database/monitors.json

      - name: Create branch
        uses: peterjgrainger/action-create-branch@v2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: v${{ env.VERSION }}

      - name: Build restful api
        run: |
          python devscript/build_restful_api.py

      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./restful
