name: Pipeline

on:
  push:
    paths:
      - '**.json'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check JSON syntax
        uses: limitusus/json-syntax-check@v1
        with:
          pattern: "\\.json$"

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Check mandatory fields
        run: |
          python devscript/check_mandatory_fields.py database.json

      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./database.json
