name: Pipeline

on:
  push:
    branches: [dev]

jobs:
  CICD:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check JSON syntax
        uses: limitusus/json-syntax-check@v1
        with:
          pattern: "database.json$"

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Check mandatory fields
        run: |
          python devscript/check_mandatory_fields.py database.json

      - name: Create MONITORS.md file
        run: |
          python devscript/create_monitors_md.py database.json

      - uses: EndBug/add-and-commit@v7
        with:
          add: 'MONITORS.md'
          message: 'Update MONITORS.md'
          push: true

      - name: Increment version
        run: |
          python devscript/increment_version.py database.json

      - uses: EndBug/add-and-commit@v7
        with:
          add: 'database.md'
          message: 'Increment the database version'
          push: true

      - name: Build Restful API
        run: |
          python devscript/build_restful_api.py database.json

      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
